/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as WorkmapsRouteImport } from './routes/workmaps'
import { Route as AgentHostSidRouteImport } from './routes/agent-host.$sid'
import { Route as CaptureSidRouteImport } from './routes/capture.$sid'
import { Route as OrgSettingsRouteImport } from './routes/org.settings'
import { Route as SandboxErpRouteImport } from './routes/sandbox.erp'
import { Route as TutorSidRouteImport } from './routes/tutor.$sid'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkmapsRoute = WorkmapsRouteImport.update({
  id: '/workmaps',
  path: '/workmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentHostSidRoute = AgentHostSidRouteImport.update({
  id: '/agent-host/$sid',
  path: '/agent-host/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureSidRoute = CaptureSidRouteImport.update({
  id: '/capture/$sid',
  path: '/capture/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxErpRoute = SandboxErpRouteImport.update({
  id: '/sandbox/erp',
  path: '/sandbox/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorSidRoute = TutorSidRouteImport.update({
  id: '/tutor/$sid',
  path: '/tutor/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/sessions': typeof SessionsRoute
  '/workmaps': typeof WorkmapsRoute
  '/agent-host/$sid': typeof AgentHostSidRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/org/settings': typeof OrgSettingsRoute
  '/sandbox/erp': typeof SandboxErpRoute
  '/tutor/$sid': typeof TutorSidRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/sessions': typeof SessionsRoute
  '/workmaps': typeof WorkmapsRoute
  '/agent-host/$sid': typeof AgentHostSidRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/org/settings': typeof OrgSettingsRoute
  '/sandbox/erp': typeof SandboxErpRoute
  '/tutor/$sid': typeof TutorSidRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/login': typeof LoginRoute
  '/people': typeof PeopleRoute
  '/sessions': typeof SessionsRoute
  '/workmaps': typeof WorkmapsRoute
  '/agent-host/$sid': typeof AgentHostSidRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/org/settings': typeof OrgSettingsRoute
  '/sandbox/erp': typeof SandboxErpRoute
  '/tutor/$sid': typeof TutorSidRoute
  '/workflows/$id': typeof WorkflowsIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/costs'
    | '/login'
    | '/people'
    | '/sessions'
    | '/workmaps'
    | '/agent-host/$sid'
    | '/capture/$sid'
    | '/org/settings'
    | '/sandbox/erp'
    | '/tutor/$sid'
    | '/workflows/$id'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costs'
    | '/login'
    | '/people'
    | '/sessions'
    | '/workmaps'
    | '/agent-host/$sid'
    | '/capture/$sid'
    | '/org/settings'
    | '/sandbox/erp'
    | '/tutor/$sid'
    | '/workflows/$id'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/costs'
    | '/login'
    | '/people'
    | '/sessions'
    | '/workmaps'
    | '/agent-host/$sid'
    | '/capture/$sid'
    | '/org/settings'
    | '/sandbox/erp'
    | '/tutor/$sid'
    | '/workflows/$id'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostsRoute: typeof CostsRoute
  LoginRoute: typeof LoginRoute
  PeopleRoute: typeof PeopleRoute
  SessionsRoute: typeof SessionsRoute
  WorkmapsRoute: typeof WorkmapsRoute
  AgentHostSidRoute: typeof AgentHostSidRoute
  CaptureSidRoute: typeof CaptureSidRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  SandboxErpRoute: typeof SandboxErpRoute
  TutorSidRoute: typeof TutorSidRoute
  WorkflowsIdRoute: typeof WorkflowsIdRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workmaps': {
      id: '/workmaps'
      path: '/workmaps'
      fullPath: '/workmaps'
      preLoaderRoute: typeof WorkmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-host/$sid': {
      id: '/agent-host/$sid'
      path: '/agent-host/$sid'
      fullPath: '/agent-host/$sid'
      preLoaderRoute: typeof AgentHostSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$sid': {
      id: '/capture/$sid'
      path: '/capture/$sid'
      fullPath: '/capture/$sid'
      preLoaderRoute: typeof CaptureSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/erp': {
      id: '/sandbox/erp'
      path: '/sandbox/erp'
      fullPath: '/sandbox/erp'
      preLoaderRoute: typeof SandboxErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/$sid': {
      id: '/tutor/$sid'
      path: '/tutor/$sid'
      fullPath: '/tutor/$sid'
      preLoaderRoute: typeof TutorSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostsRoute: CostsRoute,
  LoginRoute: LoginRoute,
  PeopleRoute: PeopleRoute,
  SessionsRoute: SessionsRoute,
  WorkmapsRoute: WorkmapsRoute,
  AgentHostSidRoute: AgentHostSidRoute,
  CaptureSidRoute: CaptureSidRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  SandboxErpRoute: SandboxErpRoute,
  TutorSidRoute: TutorSidRoute,
  WorkflowsIdRoute: WorkflowsIdRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
