/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureSidRouteImport } from './routes/capture.$sid'
import { Route as SandboxErpRouteImport } from './routes/sandbox.erp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureSidRoute = CaptureSidRouteImport.update({
  id: '/capture/$sid',
  path: '/capture/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxErpRoute = SandboxErpRouteImport.update({
  id: '/sandbox/erp',
  path: '/sandbox/erp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/sandbox/erp': typeof SandboxErpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/sandbox/erp': typeof SandboxErpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture/$sid': typeof CaptureSidRoute
  '/sandbox/erp': typeof SandboxErpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capture/$sid' | '/sandbox/erp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capture/$sid' | '/sandbox/erp'
  id: '__root__' | '/' | '/capture/$sid' | '/sandbox/erp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureSidRoute: typeof CaptureSidRoute
  SandboxErpRoute: typeof SandboxErpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture/$sid': {
      id: '/capture/$sid'
      path: '/capture/$sid'
      fullPath: '/capture/$sid'
      preLoaderRoute: typeof CaptureSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/erp': {
      id: '/sandbox/erp'
      path: '/sandbox/erp'
      fullPath: '/sandbox/erp'
      preLoaderRoute: typeof SandboxErpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureSidRoute: CaptureSidRoute,
  SandboxErpRoute: SandboxErpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
